name = "UruWorld"
author = "TheL321, Tadeta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aad1cfc06b1769e3558f047b321d30db8519de78e7e7f000e6103ea1f7d42ec7"

[versions]
forge = "0.3.33-alpha"
minecraft = "1.12.2"
