name = "UruWorld"
author = "TheL321, Tadeta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7707ee997c1d3992f2d62b6e4b3d02cc50d6293fbcc4acac59923becebd1c1d6"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
