name = "UruWorld"
author = "TheL321, Tadeta"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26b918502685fffb667eea81a34241dacbd46972cf44231f03af98fee9dc7416"

[versions]
forge = "0.3.33-alpha"
minecraft = "1.12.2"
